// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hongguo.grpc.data;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hongguo_proto_TalkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hongguo_proto_TalkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hongguo_proto_TalkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hongguo_proto_TalkResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hongguo_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hongguo_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hongguo_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hongguo_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hongguo_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hongguo_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hongguo_proto_StudentHobbyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hongguo_proto_StudentHobbyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hongguo_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hongguo_proto_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hongguo_proto_StudentResponseWrapper_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hongguo_proto_StudentResponseWrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\021com.hongguo.proto\"\032\n\013Ta" +
      "lkRequest\022\013\n\003msg\030\001 \001(\t\"\034\n\014TalkResponse\022\014" +
      "\n\004uuid\030\001 \001(\t\"\035\n\tMyRequest\022\020\n\010username\030\001 " +
      "\001(\t\"\036\n\nMyResponse\022\020\n\010realname\030\001 \001(\t\"\035\n\016S" +
      "tudentRequest\022\013\n\003age\030\001 \001(\005\"$\n\023StudentHob" +
      "byRequest\022\r\n\005hobby\030\001 \003(\t\":\n\017StudentRespo" +
      "nse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003" +
      " \001(\t\"U\n\026StudentResponseWrapper\022;\n\017studen" +
      "tResponse\030\001 \003(\0132\".com.hongguo.proto.Stud" +
      "entResponse2\376\002\n\016StudentService\022T\n\025GetRea" +
      "lNameByUsername\022\034.com.hongguo.proto.MyRe" +
      "quest\032\035.com.hongguo.proto.MyResponse\022[\n\020" +
      "GetStudentsByAge\022!.com.hongguo.proto.Stu" +
      "dentRequest\032\".com.hongguo.proto.StudentR" +
      "esponse0\001\022j\n\023GetStudentByHobbies\022&.com.h" +
      "ongguo.proto.StudentHobbyRequest\032).com.h" +
      "ongguo.proto.StudentResponseWrapper(\001\022M\n" +
      "\006BiTalk\022\036.com.hongguo.proto.TalkRequest\032" +
      "\037.com.hongguo.proto.TalkResponse(\0010\001B\'\n\025" +
      "com.hongguo.grpc.dataB\014StudentProtoP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hongguo_proto_TalkRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hongguo_proto_TalkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hongguo_proto_TalkRequest_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_com_hongguo_proto_TalkResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hongguo_proto_TalkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hongguo_proto_TalkResponse_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_com_hongguo_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hongguo_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hongguo_proto_MyRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_com_hongguo_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hongguo_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hongguo_proto_MyResponse_descriptor,
        new java.lang.String[] { "Realname", });
    internal_static_com_hongguo_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_hongguo_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hongguo_proto_StudentRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_com_hongguo_proto_StudentHobbyRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_hongguo_proto_StudentHobbyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hongguo_proto_StudentHobbyRequest_descriptor,
        new java.lang.String[] { "Hobby", });
    internal_static_com_hongguo_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_hongguo_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hongguo_proto_StudentResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "City", });
    internal_static_com_hongguo_proto_StudentResponseWrapper_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_hongguo_proto_StudentResponseWrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hongguo_proto_StudentResponseWrapper_descriptor,
        new java.lang.String[] { "StudentResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
