// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hongguo.grpc.data;

/**
 * Protobuf type {@code com.hongguo.proto.StudentHobbyRequest}
 */
public  final class StudentHobbyRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.hongguo.proto.StudentHobbyRequest)
    StudentHobbyRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentHobbyRequest.newBuilder() to construct.
  private StudentHobbyRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentHobbyRequest() {
    hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StudentHobbyRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              hobby_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            hobby_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        hobby_ = hobby_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.hongguo.grpc.data.StudentProto.internal_static_com_hongguo_proto_StudentHobbyRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.hongguo.grpc.data.StudentProto.internal_static_com_hongguo_proto_StudentHobbyRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.hongguo.grpc.data.StudentHobbyRequest.class, com.hongguo.grpc.data.StudentHobbyRequest.Builder.class);
  }

  public static final int HOBBY_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList hobby_;
  /**
   * <code>repeated string hobby = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getHobbyList() {
    return hobby_;
  }
  /**
   * <code>repeated string hobby = 1;</code>
   */
  public int getHobbyCount() {
    return hobby_.size();
  }
  /**
   * <code>repeated string hobby = 1;</code>
   */
  public java.lang.String getHobby(int index) {
    return hobby_.get(index);
  }
  /**
   * <code>repeated string hobby = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHobbyBytes(int index) {
    return hobby_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < hobby_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hobby_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < hobby_.size(); i++) {
        dataSize += computeStringSizeNoTag(hobby_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getHobbyList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.hongguo.grpc.data.StudentHobbyRequest)) {
      return super.equals(obj);
    }
    com.hongguo.grpc.data.StudentHobbyRequest other = (com.hongguo.grpc.data.StudentHobbyRequest) obj;

    if (!getHobbyList()
        .equals(other.getHobbyList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHobbyCount() > 0) {
      hash = (37 * hash) + HOBBY_FIELD_NUMBER;
      hash = (53 * hash) + getHobbyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.hongguo.grpc.data.StudentHobbyRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.hongguo.grpc.data.StudentHobbyRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.hongguo.proto.StudentHobbyRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.hongguo.proto.StudentHobbyRequest)
      com.hongguo.grpc.data.StudentHobbyRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hongguo.grpc.data.StudentProto.internal_static_com_hongguo_proto_StudentHobbyRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hongguo.grpc.data.StudentProto.internal_static_com_hongguo_proto_StudentHobbyRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hongguo.grpc.data.StudentHobbyRequest.class, com.hongguo.grpc.data.StudentHobbyRequest.Builder.class);
    }

    // Construct using com.hongguo.grpc.data.StudentHobbyRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.hongguo.grpc.data.StudentProto.internal_static_com_hongguo_proto_StudentHobbyRequest_descriptor;
    }

    @java.lang.Override
    public com.hongguo.grpc.data.StudentHobbyRequest getDefaultInstanceForType() {
      return com.hongguo.grpc.data.StudentHobbyRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.hongguo.grpc.data.StudentHobbyRequest build() {
      com.hongguo.grpc.data.StudentHobbyRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.hongguo.grpc.data.StudentHobbyRequest buildPartial() {
      com.hongguo.grpc.data.StudentHobbyRequest result = new com.hongguo.grpc.data.StudentHobbyRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        hobby_ = hobby_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.hobby_ = hobby_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.hongguo.grpc.data.StudentHobbyRequest) {
        return mergeFrom((com.hongguo.grpc.data.StudentHobbyRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.hongguo.grpc.data.StudentHobbyRequest other) {
      if (other == com.hongguo.grpc.data.StudentHobbyRequest.getDefaultInstance()) return this;
      if (!other.hobby_.isEmpty()) {
        if (hobby_.isEmpty()) {
          hobby_ = other.hobby_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureHobbyIsMutable();
          hobby_.addAll(other.hobby_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.hongguo.grpc.data.StudentHobbyRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.hongguo.grpc.data.StudentHobbyRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureHobbyIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        hobby_ = new com.google.protobuf.LazyStringArrayList(hobby_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string hobby = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHobbyList() {
      return hobby_.getUnmodifiableView();
    }
    /**
     * <code>repeated string hobby = 1;</code>
     */
    public int getHobbyCount() {
      return hobby_.size();
    }
    /**
     * <code>repeated string hobby = 1;</code>
     */
    public java.lang.String getHobby(int index) {
      return hobby_.get(index);
    }
    /**
     * <code>repeated string hobby = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHobbyBytes(int index) {
      return hobby_.getByteString(index);
    }
    /**
     * <code>repeated string hobby = 1;</code>
     */
    public Builder setHobby(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
      hobby_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string hobby = 1;</code>
     */
    public Builder addHobby(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
      hobby_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string hobby = 1;</code>
     */
    public Builder addAllHobby(
        java.lang.Iterable<java.lang.String> values) {
      ensureHobbyIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, hobby_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string hobby = 1;</code>
     */
    public Builder clearHobby() {
      hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string hobby = 1;</code>
     */
    public Builder addHobbyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureHobbyIsMutable();
      hobby_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.hongguo.proto.StudentHobbyRequest)
  }

  // @@protoc_insertion_point(class_scope:com.hongguo.proto.StudentHobbyRequest)
  private static final com.hongguo.grpc.data.StudentHobbyRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.hongguo.grpc.data.StudentHobbyRequest();
  }

  public static com.hongguo.grpc.data.StudentHobbyRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentHobbyRequest>
      PARSER = new com.google.protobuf.AbstractParser<StudentHobbyRequest>() {
    @java.lang.Override
    public StudentHobbyRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StudentHobbyRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StudentHobbyRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudentHobbyRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.hongguo.grpc.data.StudentHobbyRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

