// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hongguo.grpc.data;

public interface StudentHobbyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hongguo.proto.StudentHobbyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string hobby = 1;</code>
   */
  java.util.List<java.lang.String>
      getHobbyList();
  /**
   * <code>repeated string hobby = 1;</code>
   */
  int getHobbyCount();
  /**
   * <code>repeated string hobby = 1;</code>
   */
  java.lang.String getHobby(int index);
  /**
   * <code>repeated string hobby = 1;</code>
   */
  com.google.protobuf.ByteString
      getHobbyBytes(int index);
}
