// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hongguo.grpc.data;

public interface TalkResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hongguo.proto.TalkResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
