// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hongguo.grpc.data;

public interface TalkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hongguo.proto.TalkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
